# Generated by Django 4.1.6 on 2023-02-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_image_imageprocessing_delete_processingparammodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageprocessing',
            name='blur',
            field=models.CharField(default='default_value', max_length=1000),
        ),
    ]
