# Generated by Django 4.1.6 on 2023-02-10 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_imageprocessing_blur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageprocessing',
            name='blur',
        ),
    ]
