# Generated by Django 4.1.6 on 2023-02-13 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_imageprocessing_blur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageprocessing',
            old_name='contrast',
            new_name='mask_size',
        ),
    ]
