# Generated by Django 4.1.6 on 2023-02-13 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_contrast_imageprocessing_mask_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageprocessing',
            name='brightness',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
