# Generated by Django 4.1.6 on 2023-02-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_imageprocessing_brightness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageprocessing',
            name='brightness',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='imageprocessing',
            name='mask_size',
            field=models.IntegerField(default=1),
        ),
    ]
