# Generated by Django 4.1.6 on 2023-02-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='name', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='passwd',
            field=models.CharField(default='passwd', max_length=50),
        ),
    ]
