# Generated by Django 4.1.6 on 2023-02-15 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_user_name_alter_user_passwd'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_data',
            field=models.BinaryField(default=1),
            preserve_default=False,
        ),
    ]
