# Generated by Django 4.1.6 on 2023-02-15 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_image_image_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_data',
        ),
    ]
